version: "3.5"

services:
  mongodb_service:
    image: mongo:7.0
    command: mongod --wiredTigerCacheSizeGB 1 --maxConns 500
    environment:
      MONGO_INITDB_ROOT_USERNAME: "test"
      MONGO_INITDB_ROOT_PASSWORD: "practice"
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local
